export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS'
export const CREATE_CUSTOMER_START = 'CREATE_CUSTOMER_START'
export const CREATE_CUSTOMER_FAILURE = 'CREATE_CUSTOMER_FAILURE'
export const CREATE_CUSTOMER_END = 'CREATE_CUSTOMER_END'

export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS'
export const GET_CUSTOMERS_START = 'GET_CUSTOMERS_START'
export const GET_CUSTOMERS_FAILURE = 'GET_CUSTOMERS_FAILURE'
export const GET_CUSTOMERS_END = 'GET_CUSTOMERS_END'
